#! /bin/sh
read -p "enter the number of students " n
c=1
while [ $c -le $n ]
do 
read -p "enter the name  " name
read -p "enter the register number " r
read -p "enter the mark 1 " m1
read -p "enter the mark 2 " m2
read -p "enter the mark 3 " m3
read -p "enter the mark 4 " m4
avg=$((($m1+$m2+$m3+$m4)/4))
if [ $avg -ge 50 -a $avg -le 100 ]
	then
		s="A+"
	else 
 		s="A"
fi
echo -e "******WELCOME*****\n">$r     	
echo "REPORT CARD">>$r
echo -e "NAME OF THE STUDENT: $name">>$r
echo -e "REGISTRATION ID: $r">>$r
echo -e "AVERAGE MARKS SECURED: $avg">>$r
echo -e "GRADE SECURED: $s">>$r
c=$(($c+1))
done
